detailed git error msgs

diff --git a/run-makeref b/run-makeref
--- a/run-makeref
+++ b/run-makeref
@@ -57,17 +57,24 @@ fi
 
 
 #
-# Fetch git repo to be used as ref (target), checkout desired sha
+# Fetch git repo to be tested (target), checkout desired sha
 #
 echo
 echo "========== Cloning pull request repo"
 mkdir -p $TARGET_DIR
 cd $TARGET_DIR
-git clone $TARGET_URL .; git checkout --quiet $SHA
+git clone $TARGET_URL .
 if [ $? != 0 ]; then
   echo
   echo "***"
-  echo "ERROR: Something went wrong."
+  echo "ERROR: Could not clone $TARGET_URL"
+  exit
+fi
+git checkout --quiet $SHA
+if [ $? != 0 ]; then
+  echo
+  echo "***"
+  echo "ERROR: Could not checkout sha $SHA"
   exit
 fi
 
diff --git a/run-test b/run-test
--- a/run-test
+++ b/run-test
@@ -63,11 +63,18 @@ echo
 echo "========== Cloning pull request repo"
 mkdir -p $TARGET_DIR
 cd $TARGET_DIR
-git clone $TARGET_URL .; git checkout --quiet $SHA
+git clone $TARGET_URL .
 if [ $? != 0 ]; then
   echo
   echo "***"
-  echo "ERROR: Something went wrong."
+  echo "ERROR: Could not clone $TARGET_URL"
+  exit
+fi
+git checkout --quiet $SHA
+if [ $? != 0 ]; then
+  echo
+  echo "***"
+  echo "ERROR: Could not checkout sha $SHA"
   exit
 fi
 
